#!/bin/bash

aliasesfile="$HOME/.config/dmenu_custom/aliases"

if [[ -f "$aliasesfile" ]]
then
    readarray -t aliases < "$aliasesfile"
    for alias in "${aliases[@]}"
    do
        if [[ $alias = "alias"*"="* ]]
        then
            echo "${alias//alias /}" | awk -F "=" '{print $1}' 
        fi
    done
fi