#!/bin/bash

cachedir="$HOME/.cache"
cache="$cachedir/dmenu_run"
cache_desktop_global="$cachedir/dmenu_desktop_global"
cache_desktop_local="$cachedir/dmenu_desktop_local"
cache_desktop_cmd_global="$cachedir/dmenu_desktop_cmd_global"
cache_desktop_cmd_local="$cachedir/dmenu_desktop_cmd_local"

rebuild_desktop_cache()
{
	rm "$2"
	readarray -t files < "$1"
	for file in "${files[@]}"
	do
		if [[ $file = *.desktop ]]
		then
			if ! [[ $(awk -F "=" '/NoDisplay=/ {print $2}' "$file") = "true" && \
					$(awk -F "=" '/Hidden=/ {print $2}' "$file") = "true" ]]
			then
				name=$(grep -v GenericName "$file" | awk -F "=" '/Name=/ {print $2}' | awk NR==1)
				exec=$(grep "Exec=" "$file" | sed 's/Exec=//g' | awk -F "%" '{print $1}' | awk NR==1)

				if [[ -n $(awk -F "=" '/Path=/ {print $2}' "$file") ]]
				then
					exec="pushd ""$(awk -F "=" '/Path=/ {print $2}' "$file")"" && ""$exec"
				fi

				if [[ $(awk -F "=" '/Terminal=/ {print $2}' "$file") = "true" ]]
				then
					output=$name", $TERM -e $SHELL -c '""$exec""'"
				else
					output=$name", "$exec
				fi

				echo $output >> "$2"
			fi
		fi
	done
}

check_rebuild_cache()
{
	local IFS=:
	if stest -dqr -n "$1" $PATH
	then
		stest -flx $PATH | sort -u >> "$1"
	fi
}

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

check_rebuild_cache "$cache"

if stest -dqr -n "$cache_desktop_global" "/usr/share/applications" || \
   ! cat "$cache_desktop_global"
then
	find /usr/share/applications/ -type f > "$cache_desktop_global"
	rebuild_desktop_cache "$cache_desktop_global" "$cache_desktop_cmd_global"
fi

if stest -dqr -n "$cache_desktop_local" "$HOME/.local/share/applications" || \
   ! cat "$cache_desktop_local"
then
	find $HOME/.local/share/applications -type f > "$cache_desktop_local"
	rebuild_desktop_cache "$cache_desktop_local" "$cache_desktop_cmd_local"
fi
