#!/bin/bash

cachedir="$HOME/.cache/dmenu_custom"
configdir="$HOME/.config/dmenu_custom"
aliasesfile="$configdir/aliases"
lockfile="$cachedir/lock"
cache_desktop_cmd_global="$cachedir/dmenu_desktop_cmd_global"
cache_desktop_cmd_local="$cachedir/dmenu_desktop_cmd_local"

checkrunning()
{
    if [[ -f "$lockfile" ]]
    then
        echo "Already running!"
        exit 1
    else
        touch "$lockfile"
    fi
}

execute()
{
    if [[ -n $1 ]]
    then
        if [[ -f "$aliasesfile" ]] && grep -qF "$1=" "$aliasesfile"
        then
            cmd=$(grep "$1=" "$aliasesfile" | sed "s/alias $1=//g")
        elif grep -qF "$1;" "$cache_desktop_cmd_global"
        then
            cmd=$(grep "$1;" "$cache_desktop_cmd_global" | awk -F "; " '{print $2}')
        elif grep -qF "$1" "$cache_desktop_cmd_local"
        then
            cmd=$(grep "$1" "$cache_desktop_cmd_local" | awk -F "; " '{print $2}')
        else
            cmd="$1"
        fi
        printf "$cmd" | ${SHELL:-"/bin/sh"}
    fi
}

checkrunning
selection=$( (dmenu_path && dmenu_desktop && dmenu_aliases) | sort -u | dmenu "$@" )
rm "$lockfile"
execute "$selection"
