#!/usr/bin/python3

import os
import sys
from pathlib import Path
from configparser import ConfigParser

home = os.path.expanduser("~/")
cachedir = home + ".cache/dmenu_custom/"
dirs = (
    (
        cachedir + "dmenu_desktop_global",
        cachedir + "dmenu_desktop_local",
        cachedir + "dmenu_desktop_flatpak_global",
        cachedir + "dmenu_desktop_flatpak_local"
    ),
    (
        cachedir + "dmenu_desktop_cmd_global",
        cachedir + "dmenu_desktop_cmd_local",
        cachedir + "dmenu_desktop_cmd_flatpak_global",
        cachedir + "dmenu_desktop_cmd_flatpak_local"
    )
    (
        "/usr/share/applications/",
        home + ".local/share/applications/",
        "/var/lib/flatpak/exports/share/applications/",
        home + ".local/flatpak/exports/share/applications/"
    )
)

def get_desktop_details(file):
    if file.endswith(".desktop"):
        config = ConfigParser(interpolation=None)
        config.read(file)
        desktop = config["Desktop Entry"]
        if config.has_option("Desktop Entry", "NoDisplay") and desktop["Nodisplay"] == "true":
            exit(1)
        if config.has_option("Desktop Entry", "Hidden") and desktop["Hidden"] == "true":
            exit(1)
        name = desktop["Name"]
        exec = desktop["Exec"].split(" %")[0]
        if config.has_option("Desktop Entry", "Path"):
                exec = "pushd \"" + desktop["Path"] + "\" && " + exec
        if config.has_option("Desktop Entry", "Terminal") and desktop["Terminal"] == "true":
            exec = os.environ["TERM"] + " -e " + os.environ["SHELL"] + " -c '" + exec + "'"
        print(name + "; " + exec + "; " + file)