#!/bin/bash

cachedir="$HOME/.cache/dmenu_custom"
configdir="$HOME/.config/dmenu_custom"
lockfile="$cachedir/lock"
aliasesfile="$configdir/aliases"
cmdcaches=(
    "$cachedir/dmenu_desktop_cmd_global"
    "$cachedir/dmenu_desktop_cmd_local"
    "$cachedir/dmenu_desktop_cmd_flatpak_global"
    "$cachedir/dmenu_desktop_cmd_flatpak_local"
)

checkrunning()
{
    [ ! -e "$cachedir" ] && mkdir -p "$cachedir"

    if [[ -f "$lockfile" ]]
    then
        echo "Already running!"
        exit 1
    else
        touch "$lockfile"
    fi
}

execute()
{
    if [[ -n $1 ]]
    then
        if [[ -f "$aliasesfile" ]] && grep -qF "alias $1=" "$aliasesfile"
        then
            cmd=$(grep "alias $1=" "$aliasesfile" | sed "s/alias $1=//g")
        fi
        if [[ -z $cmd ]]
        then
            for cachefile in "${cmdcaches[@]}"
            do
                if [[ -f "$cachefile" ]] && grep -q "^$1;" "$cachefile"
                then
                    cmd=$(grep "^$1;" "$cachefile" | awk -F "; " '{print $2}')
                fi
            done
        fi
        if [[ -z $cmd ]]
        then
            cmd="$1"
        fi
        printf "$cmd" | ${SHELL:-"/bin/sh"}
    fi
}

checkrunning
entries=$( (dmenu_path && dmenu_desktop && dmenu_aliases) 2>/dev/null | sort -u )
selection=$(echo "${entries[@]}" | dmenu "$@")
rm "$lockfile"
if [[ -n $selection ]]
then
    execute "$selection"
fi