#!/bin/bash

cachedir="$HOME/.cache/dmenu_custom"
configdir="$HOME/.config/dmenu_custom"
lockfile="$cachedir/lock"
aliasesfile="$configdir/aliases"
excludefile="$configdir/excludes"
namecaches=(
    "$cachedir/dmenu_desktop_names_global"
    "$cachedir/dmenu_desktop_names_global_local"
    "$cachedir/dmenu_desktop_names_local"
    "$cachedir/dmenu_desktop_names_flatpak_global"
    "$cachedir/dmenu_desktop_names_flatpak_local"
)

checkrunning()
{
    if [[ -f "$lockfile" ]]
    then
        echo "Already running!"
        exit 1
    fi
}

execute()
{
    if [[ -n $1 ]]
    then
        if [[ -f "$aliasesfile" ]] && grep -qF "alias $1=" "$aliasesfile"
        then
            eval "$(grep "alias $1=" "$aliasesfile" | sed "s/alias $1=//g")"
        else
            for namecache in "${namecaches[@]}"
            do
                if [[ -f "$namecache" ]] && grep -q "^$1;" "$namecache"
                then
                    dex --term alacritty "$(grep "^$1;" "$namecache" | awk -F "; " '{print $2}')"
                    return
                fi
            done
            $1
        fi
    fi
}

checkrunning
entries=$( (dmenu_desktop && dmenu_aliases) 2>/dev/null | sort -u )
if [[ -f "$excludefile" ]]
then
    readarray -t excludes < "$excludefile"
    for exclude in "${excludes[@]}"
    do
        if grep -qx "$exclude" <(echo "${entries[@]}")
        then
            entries=$(echo "${entries[@]}" | sed "/$exclude/d")
        fi
    done
fi
selection=$(echo "${entries[@]}" | dmenu "$@")
execute "$selection"