#!/bin/bash

cachedir="$HOME/.cache/dmenu_custom"
lockfile="$cachedir/lock"
filecaches=(
	"$cachedir/dmenu_desktop_global"
	"$cachedir/dmenu_desktop_local"
	"$cachedir/dmenu_desktop_flatpak_global"
	"$cachedir/dmenu_desktop_flatpak_local"
)
cmdcaches=(
    "$cachedir/dmenu_desktop_cmd_global"
    "$cachedir/dmenu_desktop_cmd_local"
    "$cachedir/dmenu_desktop_cmd_flatpak_global"
    "$cachedir/dmenu_desktop_cmd_flatpak_local"
)
desktopdirs=(
	"/usr/share/applications/"
	"$HOME/.local/share/applications/"
	"/var/lib/flatpak/exports/share/applications/"
	"$HOME/.local/flatpak/exports/share/applications/"
)

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

checkrunning()
{
    [ ! -e "$cachedir" ] && mkdir -p "$cachedir"

    if [[ -f "$lockfile" ]]
    then
        echo "Already running!"
        exit 1
    else
        touch "$lockfile"
    fi
}

get_desktop_details()
{
	if [[ $1 = *.desktop ]]
	then
		if ! [[ $(awk -F "=" '/NoDisplay=/ {print $2}' "$1") = "true" && $(awk -F "=" '/Hidden=/ {print $2}' "$1") = "true" ]]
		then
			name=$(grep -v GenericName "$1" | awk -F "=" '/Name=/ {print $2}' | awk NR==1)
			exec=$(grep "Exec=" "$1" | sed 's/Exec=//g' | awk -F "%" '{print $1}' | awk NR==1)

			if [[ -n $(grep -v X-DocPath "$1" | awk -F "=" '/Path=/ {print $2}') ]]
			then
				exec="pushd \"""$(awk -F "=" '/Path=/ {print $2}' "$1")""\" && ""$exec"
			fi

			if [[ $(awk -F "=" '/Terminal=/ {print $2}' "$1") = "true" ]]
			then
				exec="alacritty -e $SHELL -c '""$exec""'"
			fi

			output="$name""; ""$exec""; ""$1"

			echo "$output"
		fi
	fi
}

rebuild_desktop_cache()
{
	[[ -f "$2" ]] && rm "$2"
	readarray -t files < "$1"
	for file in "${files[@]}"
	do
		get_desktop_details "$file" >> "$2"
	done
}

add_remove_desktop()
{
	local changes="$1"
	for i in $(seq 1 "$(echo "${changes[@]}" | wc -l)")
	do
		change="$(echo "${changes[@]}"| awk NR=="$i")"
		if [[ "$change" = ">"* ]]
		then
			file="${change//> /}"
			get_desktop_details "$file" >> "$2"
		elif [[ "$change" = "<"* ]]
		then
			file="$(sed 's/\//\\\//g' <<<"${change//< /}")"
			sed -i "/$file/d" "$2"
		fi
	done
}

check_change_desktop()
{
	if [[ -d "$3" ]]
	then
		if [[ ! -f "$1" || ! -f "$2" ]]
		then
			find "$3" -type f,l -name "*.desktop" > "$1"
			rebuild_desktop_cache "$1" "$2"
		elif [[ -n $(diff "$1" <(find "$3" -type f,l -name "*.desktop")) ]]
		then
			diff=$(diff "$1" <(find "$3" -type f,l -name "*.desktop"))
			add_remove_desktop "${diff[@]}" "$2"
			find "$3" -type f,l -name "*.desktop" > "$1"
		fi
		awk -F "; " '{print $1}' "$2"
	fi
}

checkrunning
for i in $(seq 0 $((${#desktopdirs[@]} - 1)))
do
	check_change_desktop "${filecaches[i]}" "${cmdcaches[i]}" "${desktopdirs[i]}"
done
rm "$lockfile"