#!/bin/bash

cachedir="$HOME/.cache/l7-dmenu-desktop"
configdir="$HOME/.config/l7-dmenu-desktop"
lockfile="$cachedir/lock"
aliasescache="$cachedir/dmenu_aliases"
aliasesnamecache="$cachedir/dmenu_aliases_names"
aliasesfile="$configdir/aliases"

checkrunning()
{
    [ ! -e "$1" ] && mkdir -p "$1"
    if [[ -f "$2" ]]
    then
        echo "Already running!"
        exit 1
    else
        touch "$2"
    fi
}

get_alias_name()
{
    if [[ $1 = "alias "*"="* ]]
    then
        echo "${1//alias /}" | awk -F "=" '{print $1}'
    fi
}

add_remove_alias()
{
	changes="$1"
	for i in $(seq 1 "$(echo "${changes[@]}" | wc -l)")
	do
		change="$(echo "${changes[@]}"| awk NR=="$i")"
		if [[ "$change" = ">"* ]]
		then
			alias="${change//> /}"
			get_alias_name "$alias" >> "$2"
		elif [[ "$change" = "<"* ]]
		then
			alias="${change//< /}"
			sed -i "/$(get_alias_name "$alias")/d" "$2"
		fi
	done
}

check_change_desktop()
{
	if [[ -f "$3" ]]
	then
		if [[ ! -f "$1" || ! -f "$2" ]]
		then
			[[ -f "$2" ]] && rm "$2"
			cp -f "$3" "$1"
            readarray -t aliases < "$1"
            for alias in "${aliases[@]}"
            do
                get_alias_name "$alias" >> "$2"
            done
		elif ! diff -q "$1" "$3" >/dev/null 2>&1
		then
			diff=$(diff "$1" "$3")
            cp -f "$3" "$1"
			add_remove_alias "${diff[@]}" "$2"
		fi
		cat "$2"
	fi
}

checkrunning "$cachedir" "$lockfile"
check_change_desktop "$aliasescache" "$aliasesnamecache" "$aliasesfile"
rm "$lockfile"