#!/bin/bash

cachedir="$HOME/.cache/dmenu"
cache="$cachedir/dmenu_desktop_run"
cache_desktop_global="$cachedir/dmenu_desktop_global"
cache_desktop_local="$cachedir/dmenu_desktop_local"
cache_desktop_diff="$cachedir/dmenu_desktop_diff"
cache_desktop_cmd_global="$cachedir/dmenu_desktop_cmd_global"
cache_desktop_cmd_local="$cachedir/dmenu_desktop_cmd_local"

get_desktop_details()
{
	if [[ $1 = *.desktop ]]
	then
		if ! [[ $(awk -F "=" '/NoDisplay=/ {print $2}' "$1") = "true" && \
				$(awk -F "=" '/Hidden=/ {print $2}' "$1") = "true" ]]
		then
			name=$(grep -v GenericName "$1" | awk -F "=" '/Name=/ {print $2}' | awk NR==1)
			exec=$(grep "Exec=" "$1" | sed 's/Exec=//g' | awk -F "%" '{print $1}' | awk NR==1)

			if [[ -n $(awk -F "=" '/Path=/ {print $2}' "$1") ]]
			then
				exec="pushd \"""$(awk -F "=" '/Path=/ {print $2}' "$1")""\" && ""$exec"
			fi

			if [[ $(awk -F "=" '/Terminal=/ {print $2}' "$1") = "true" ]]
			then
				exec="$TERM -e $SHELL -c '""$exec""'"
			fi

			output="$name""; ""$exec""; ""$1"

			echo "$output"
		fi
	fi
}

rebuild_desktop_cache()
{
	rm "$2"
	readarray -t files < "$1"
	for file in "${files[@]}"
	do
		get_desktop_details "$file" >> "$2"
	done
}

add_remove_desktop()
{
	readarray -t changes < "$1"
	for change in "${changes[@]}"
	do
		if [[ "$change" = ">"* ]]
		then
			file="$(echo $change | sed 's/> //g')"
			get_desktop_details "$file" >> "$2"
		elif [[ "$change" = "<"* ]]
		then
			file="$(echo $change | sed 's/< //g' | sed 's/\//\\\//g')"
			sed -i "/$file/d" "$2"
		fi
	done
}

check_rebuild_cache()
{
	local IFS=:
	if stest -dqr -n "$1" $PATH
	then
		stest -flx $PATH | sort -u >> "$1"
	fi
}

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

check_rebuild_cache "$cache"

if [[ -n $(diff "$cache_desktop_global" <(find /usr/share/applications/ -type f -name "*.desktop")) ]] || ! cat "$cache_desktop_global"
then
	if ! cat "$cache_desktop_cmd_global" || ! cat "$cache_desktop_global"
	then
		find /usr/share/applications/ -type f -name "*.desktop" > "$cache_desktop_global"
		rebuild_desktop_cache "$cache_desktop_global" "$cache_desktop_cmd_global"
	else
		diff "$cache_desktop_global" <(find /usr/share/applications/ -type f -name "*.desktop") > "$cache_desktop_diff"
		add_remove_desktop "$cache_desktop_diff" "$cache_desktop_cmd_global"
		find /usr/share/applications/ -type f -name "*.desktop" > "$cache_desktop_global"
	fi
fi

if [[ -n $(diff "$cache_desktop_local" <(find $HOME/.local/share/applications -type f -name "*.desktop")) ]] || ! cat "$cache_desktop_local"
then
	if ! cat "$cache_desktop_cmd_local" || ! cat "$cache_desktop_local"
	then
		find $HOME/.local/share/applications -type f -name "*.desktop" > "$cache_desktop_local"
		rebuild_desktop_cache "$cache_desktop_local" "$cache_desktop_cmd_local"
	else
		diff "$cache_desktop_local" <(find $HOME/.local/share/applications -type f -name "*.desktop") > "$cache_desktop_diff"
		add_remove_desktop "$cache_desktop_diff" "$cache_desktop_cmd_local"
		find $HOME/.local/share/applications -type f -name "*.desktop" > "$cache_desktop_local"
	fi
fi
