#!/bin/bash

if [[ $(pgrep -f dmenu_run_desktop | wc -l) != 2 ]]
then
    echo "Already running!"
    exit 1
fi

cachedir="$HOME/.cache/dmenu_desktop"
cache_desktop_cmd_global="$cachedir/dmenu_desktop_cmd_global"
cache_desktop_cmd_local="$cachedir/dmenu_desktop_cmd_local"

execute()
{
    if [[ -n $1 ]]
    then
        if grep -qF "$1" "$cache_desktop_cmd_global"
        then
            cmd=$(grep "$1" "$cache_desktop_cmd_global" | awk -F "; " '{print $2}')
            printf "$cmd" | ${SHELL:-"/bin/sh"}
        elif grep -qF "$1" "$cache_desktop_cmd_local"
        then
            cmd=$(grep "$1" "$cache_desktop_cmd_local" | awk -F "; " '{print $2}')
            printf "$cmd" | ${SHELL:-"/bin/sh"}
        else
            $1
        fi
    fi
}

selection=$( (dmenu_path_desktop && dmenu_path) | sort -u | dmenu "$@" )
execute "$selection"
